### ISSUE TITLE
[Android bootcamp] Review my project #3: TweetMe

### ISSUE THREAD

**Issue by simonque** [simonque/tweetme#1]
/cc @nesquena @thecodepath

**Comment by vibhorB** [comment]
:+1: nice work Simon. A few notes after checking out the code:
- Good to see you were able to format the timestamp cleanly
- Nice to see you used a PullToRefresh library for easy timeline refreshes
- Good to see you refreshed the timeline after composing a new tweet
- Nice touch with the character count being displayed while the user composes a tweet
- Consider adding progress bars to your app whenever a network request goes out
- Consider adding local persistence of tweets by using ActiveAndroid in the Tweet and User
- Consider [better organizing your source files](http://guides.codepath.com/android/Organizing-your-Source-Files)
- Pls refer to twitter api docs, your "reply" feature implementation is not correct

Here's a detailed [Project 3 Feedback Guide here](https://gist.github.com/nesquena/a41220c54c9550f69599) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, ActionBar, Navigation, Models, Authentication, API Communication, Persistence, et al) and see how they all fit together. We are close now to a turning point in the course where you should be hitting a "critical mass" towards your knowledge of Android.
